# roles/mysql_server/tasks/main.yml
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: true
